/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   10_utils_free.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: anemet <anemet@student.42luxembourg.lu>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/07/10 16:12:09 by anemet            #+#    #+#             */
/*   Updated: 2025/07/10 16:19:07 by anemet           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "push_swap.h"

// frees all nodes in a stack
// iterates through linke list, freeing each node one by one
void	free_stack(t_stack **stack)
{
	t_stack	*current_node;
	t_stack	*next_node;

	if (!stack || !*stack)
		return ;
	current_node = *stack;
	while (current_node)
	{
		next_node = current_node->next;
		free(current_node);
		current_node = next_node;
	}
	*stack = NULL;
}

// frees a null-terminated array of strings - as one from generated by ft_split
void	free_split(char **split_args)
{
	int	i;

	i = 0;
	if (!split_args)
		return ;
	while (split_args[i])
	{
		free(split_args[i]);
		i++;
	}
	free(split_args);
}

// frees both stacks, prints "Error\n" to STDERR and exits the program
// this is an error-handling function for the entire project
void	error_exit(t_stack **a, t_stack **b)
{
	free_stack(a);
	free_stack(b);
	ft_putendl_fd("Error", 2);
	exit(1);
}
